Fix SteamVR complaining about sync on restarts
alvr-org/ALVR pull request #1158
Opened 2022-08-24 20:59 UTC by Meister1593

Currently, ALVR closes itself and restarts, but by doing so Steam still thinks that it is running (because Steam treats any process that is launched from him as working one, until it is completely closed).
So, in this PR i refactored launcher and made it as a control process for alvr server driver. Now when driver wants to restart, shutdown, or update itself it talks to launcher process now using sockets.
I also made sure that if for whatever reason driver won't send exit signal to launcher, it won't be in the background forever (basically, a watcher that checks for existence of steamvr processes).

I've tested mostly with v18 branch before upstreaming to v19 (with headset), but on v19 it behaves on just restarts from dashboard exactly the same. Would be nice if multiple people test this before merging.
I did not test update mechanism, but as far as i am concerned, it should behave exactly the same as before.

2022-08-24 21:10 UTC, zarik5 requested changes
Overall looks good (not tested). The "control" nomenclature is already used for the client communication. Please rename "control messages", "control packet" etc to "launcher control ..." or just "launcher ...".

2022-08-24 21:24 UTC, Meister1593 commented
Renamed 'control' to 'launcher' and 'client' to 'driver'

2022-08-24 21:50 UTC, zarik5 approved these changes

2022-08-24 22:52 UTC, Meister1593 commented
I might have forgotten a check for updater - when it is running, it might not have steamvr running for a while and it could kill itself. Probably need to check that behavior just in case.

2022-08-25 10:33 UTC, Meister1593 commented
> I might have forgotten a check for updater - when it is running, it might not have steamvr running for a while and it could kill itself. Probably need to check that behavior just in case.

I will probably test today Windows behaviour with what i did, i'm not quite sure how updating behaviour works on windows, but it seems like spawning without window doesn't actually kill entire process tree

2022-08-25 18:22 UTC, Meister1593 commented
> > I might have forgotten a check for updater - when it is running, it might not have steamvr running for a while and it could kill itself. Probably need to check that behavior just in case.
> 
> I will probably test today Windows behaviour with what i did, i'm not quite sure how updating behaviour works on windows, but it seems like spawning without window doesn't actually kill entire process tree

After testing it seems like that spawning process on windows beahves slightly differently and after closing launcher, it doesn't kill updater process.
I made a notice for non-windows OS (just a precaution if it ever happens) and exit after launching installer immediately instead of waiting for timeouts.

Testers now should check if it works and it should be good to go

2022-08-26 17:16 UTC, Meister1593 commented
Tested myself for couple of days of running it (on v18 with the same changes), worked pretty well so far, restarts from game, outside of game, closing, etc.

2022-08-30 10:47 UTC, Meister1593 commented
Okay don't merge this yet, i might have really over-engineered all of this.
Disowning the process is actually incredibly easy on linux and i will look into the disowning the process on windows (possibly through explorer.exe).
This might be a lot simpler than i initially thought.

2022-10-09 22:02 UTC, zarik5 commented
Will this be moved forward? This is still a problem for many, including myself. My company uses an offline version of SteamVR, which also requires changing the launch code in the launcher to execute the right SteamVR version. But this cannot be required for common users.

2022-10-21 16:32 UTC, closed without merging

2022-10-21 16:40 UTC, Meister1593 commented
I felt like this approach isn't the best and way too overcomplicated