Various refactoring
alvr-org/ALVR pull request #1439
Opened 2023-02-05 20:37 UTC by deiteris

1. Rename `alvr_client_core::poll_event()` to `alvr_client_core::get_event()` and corresponding C function from `alvr_poll_event()` to `alvr_get_event()`. This function doesn't do any polling and just pops the event from the queue.
2. Use `thread::yield_now()` instead of sleep in render loop. 1ms sleep introduces additional 1ms client compositor latency for little benefit.
3. Use `thread::yield_now()` in decoder thread. Same as above, this should help to avoid additional latency and give time for other threads.
4. Remove "Video frame queue underflow!" when attempting to dequeue a frame and place "Timed out when waiting for frame!" warning when the frame dequeue function timed out. Queue polling triggers this warning lots of times under almost any condition and creates a huge log spam.
5. Refactor VSync thread to start up with proper frame interval from the beginning.

For verification, CPU/GPU load with `sleep()`:
![image](https://user-images.githubusercontent.com/6103913/216842316-f8105dfb-cf7c-4896-9651-465b1868d60a.png)

CPU/GPU load with `yield_now()`:
![image](https://user-images.githubusercontent.com/6103913/216842153-b8638d39-5fb7-4aaa-9d4e-eb3c1110537c.png)

2023-02-05 21:35 UTC, zarik5 commented
I'm not sure there is any semantic difference between `poll_event` and `get_event`. That is, for me they are interchangeable. I think "poll" is valid used here and clearly opposed to the pattern of event subscription (ie callback).

2023-02-05 21:41 UTC, zarik5 commented
@deiteris Your change for the vsync thread undoes the fix I did for #1388. We should start generating vsync before the client fps negotiation.

2023-02-05 21:44 UTC, deiteris commented
> I'm not sure there is any semantic difference between `poll_event` and `get_event`. That is, for me they are interchangeable. I think "poll" is valid used here and clearly opposed to the pattern of event subscription (ie callback). OpenXR also uses `poll_event` with similar semantic and inner workings.

You can check OpenXR's `.poll_event()` method and see that it actually loops until the event is obtained (i.e., it pools), while our method just gets the result (it doesn't poll itself).

> @deiteris Your change for the vsync thread undoes the fix I did for #1388. We should start generating vsync before the client fps negotiation.

But `.recv()` blocks until the message is received. VSync will not be generated before that, and with the logic, it will generate a VSync with 20ms interval.

2023-02-05 21:46 UTC, zarik5 requested changes

2023-02-05 21:46 UTC, zarik5 commented on alvr/client_core/src/platform/android.rs
> -
Do not delete this line, instead comment it and add:
```
// todo: add back when implementing proper phase sync
```

2023-02-05 21:51 UTC, zarik5 commented
> You can check OpenXR's .poll_event() method and see that it actually loops until the event of required result is obtained (i.e., it polls for the event), while our method just gets the result (it doesn't poll itself but gives out instant result).

Nope, OpenXR does not work like that. Events are generated and queued internally. A hint for this is the `EventsLost` event when the internal buffer is full (instead we don't limit the internal buffer).

> But .recv() blocks until the message is received. VSync will not be generated before that, and with the logic, it will generate a VSync with 20ms interval.

Exactly, we don't want this behavior. We want to generate vsyncs as soon as the ALVR driver is alive, way before a client is discovered and connected.

2023-02-05 22:10 UTC, deiteris commented
> Exactly, we don't want this behavior. We want to generate vsyncs as soon as the ALVR driver is alive, way before a client is discovered and connected.

Huh, okay, dropping this one.

> Nope, OpenXR does not work like that. Events are generated and queued internally. A hint for this is the `EventsLost` event when the internal buffer is full (instead we don't limit the internal buffer).

Then it sounds like this method doesn't actually do any polling and I don't understand why it would require a loop to get an event (and return regardless of whether an event was available). But our method is a simple getter either way.

2023-02-06 00:25 UTC, Vixea commented
I think this can be merged do you want me to test this first or the ffr pr(option 2)

2023-02-06 11:27 UTC, deiteris commented
@Vixea you can test both. FFR pull request will have only cosmetic change a bit later.

2023-02-07 20:45 UTC, zarik5 approved these changes

2023-02-07 20:45 UTC, merged