Driver: Refactor Hmd and Controller
alvr-org/ALVR pull request #1452
Opened 2023-02-12 23:24 UTC by Vixea

2023-02-13 22:45 UTC, deiteris commented on alvr/server/cpp/alvr_server/alvr_server.cpp
> +    std::shared_ptr<Controller> left_controller, right_controller;
All these pointers aren't not shared. Just use `unique_ptr`.

2023-02-13 22:45 UTC, deiteris commented on alvr/server/cpp/alvr_server/alvr_server.cpp
> +                this->tracked_devices.insert({LEFT_HAND_ID, (TrackedDevice *)&*this->left_controller});
```suggestion
                this->tracked_devices.insert({LEFT_HAND_ID, (TrackedDevice *)this->left_controller.get()});
```

2023-02-13 22:46 UTC, deiteris commented on alvr/server/cpp/alvr_server/alvr_server.cpp
> +                    {RIGHT_HAND_ID, (TrackedDevice *)&*this->right_controller});
```suggestion
                    {RIGHT_HAND_ID, (TrackedDevice *)this->right_controller.get()});
```

2023-02-13 22:47 UTC, deiteris commented on alvr/server/cpp/alvr_server/alvr_server.cpp
> +    std::shared_ptr<Controller> controller;
Seems to be unused?

2023-02-13 23:15 UTC, deiteris commented on alvr/server/cpp/alvr_server/alvr_server.cpp
> +                    vr::TrackedDeviceClass_Controller, //right_controller->getControllerDeviceClass(), can't solve linking error so leaving it like this for now
The issue with linker is that this is not member of the class. You added a method prototype `Controller.h`, tried to reference, but there's no implementation in cpp.

2023-02-15 22:04 UTC, zarik5 requested changes
Looks good, but please format the files you modified (i just run alt+shift+F on vscode).

2023-02-16 00:49 UTC, zarik5 approved these changes

2023-02-16 00:49 UTC, merged