separate quality presets for amd and nvenc
alvr-org/ALVR pull request #1546
Opened 2023-03-30 15:35 UTC by galister

Includes nvenc dropdown for p1-p7
Amd dropdown for Speed, Quality, Balanced
Preset on top for Speed, Quality, Balanced

2023-03-30 20:32 UTC, zarik5 requested changes

2023-03-30 20:32 UTC, zarik5 commented on alvr/server/cpp/platform/linux/EncodePipeline.cpp
> +    Info("SetParams: %u, %u @ %f", params.updated, params.bitrate_bps / 1'000'000UL, params.framerate);
This should probably be removed.

2023-03-30 20:32 UTC, zarik5 commented on alvr/session/src/settings.rs
> +    P7 = 6,
I'm thinking it should be P1 = 1, P2 = 2 etc. Less surprising.

2023-03-30 20:32 UTC, zarik5 commented on alvr/dashboard/src/dashboard/components/settings_controls/presets/builtin_schema.rs
> +                    "session_settings.video.advanced_codec_options.nvenc_overrides.nvenc_quality_preset",
I haven't tested this, but I think you are missing a ".variant" at the end of the path. Same after amd_encoder_quality_preset below.

2023-03-31 12:34 UTC, galister commented
@zarik5 tested and ready

2023-03-31 12:50 UTC, zarik5 requested changes

2023-03-31 13:50 UTC, zarik5 commented
Alright that's good enough 👍

2023-03-31 13:50 UTC, zarik5 approved these changes

2023-03-31 13:51 UTC, merged