fix: alvr_client_core stability issues on smartphone androids
alvr-org/ALVR pull request #1586
Opened 2023-04-15 12:57 UTC by ShootingKing-AM

- Building for x86 arch enables faster AVD emulation
- Android enforces only x86 emulator images to run on x86 hosts from API 28 - https://stackoverflow.com/a/74819011

2023-04-15 17:31 UTC, zarik5 requested changes
if you add another target (x86_64) expose it as a flag in xtask. You also need to expose it for prepare-deps to download the toochain.

You don't need to expose a low latency flag. you are just modifying settings defaults, which should be accessed from the dashboard directly. The issue is that we didn't implement support for dictionaries yet.

2023-04-15 17:31 UTC, zarik5 commented on alvr/client_core/src/platform/android.rs
> +            info!("Using AMediaCoded format:{} ", format);
Remove logging

2023-04-16 13:20 UTC, ShootingKing-AM commented
> if you add another target (x86_64) expose it as a flag in xtask. 
I felt that it would be redundant, let us build the client_core for widest compatibility and let the client implementation choose which ever ABI they wish to use (which gradle/cmake would automatically pickup). I actually wanted to do `-t arm64-v8a -t armeabi-v7a -t x86_64 -t x86` but was waiting for aforementioned issues to be solve.

> You also need to expose it for prepare-deps to download the toochain.
True, that would be a pr to alvr-cardboard repo

> You don't need to expose a low latency flag. you are just modifying settings defaults, which should be accessed from the dashboard directly. The issue is that we didn't implement support for dictionaries yet.
True, its actually weird that low-latency (well documented flag) crashes with UNKNOWN error. That is default enabled on alvr_client_core, and crashes smartphone androids. I don't think we can request all smartphone android implementations to post installation first goto alvr dashboard and disable that flag :( Thought this would be best wayforward. what do you suggest ?

2023-04-16 19:12 UTC, zarik5 commented
> True, its actually weird that low-latency (well documented flag) crashes with UNKNOWN error. That is default enabled on alvr, and crashes smartphone androids. I don't think we can request all smartphone android implementations to post installation first goto alvr dashboard and disable that flag :( Thought default-enabled-feature would be best wayforward. what do you suggest ?

This is what I expected the user to do e.g. for an earlier version, where FFR would break the image on the GearVR. But indeed I agree we should apply fixes automatically if possible. The tricky part is detecting which devices support the flag and which don't. Also settings are set on the server side, so the feature flag you put doesn't make sense. My solution would be to add the feature flag on alvr_client_core, and when the client receives the mediacodec options, search for the low-latency entry and remove it conditionally.

2023-04-17 08:32 UTC, ShootingKing-AM commented
> This is what I expected the user to do e.g. for an earlier version, where FFR would break the image on the GearVR. But indeed I agree we should apply fixes automatically if possible. The tricky part is detecting which devices support the flag and which don't. Also settings are set on the server side, so the feature flag you put doesn't make sense. My solution would be to add the feature flag on alvr_client_core, and when the client receives the mediacodec options, search for the low-latency entry and remove it conditionally.

This is exactly what I did. `alvr/alvr_client_core` uses `alvr/session` too. When client_core is built its pulling in `session/settings`. And by default, server or default alvr_client_core, when using `alvr/sessions` will have low-latency enabled. Only when `alvr_client_core` is built with `--no-default-features`, `low-latency` will be removed from `alvr/sessions` and pulled into `alvr_client_core`. `alvr/sessions` is rightly being shared between client and server. I have tested this.

2023-04-17 09:23 UTC, zarik5 commented
No, it's not working correctly. Changing the defaults on the client will do nothing since the settings are pulled from the server. If it works for you it's because you recompile the server without the flag and we don't want to have a separate server build for the cardboard version.

2023-04-20 16:16 UTC, ShootingKing-AM commented
- removed default "low-latency" flag, since it crashes on some clients
- Upstream merged fixes (https://github.com/rust-lang/socket2/pull/434), now can build for all ABIs

2023-04-21 13:19 UTC, zarik5 commented
That's good. So in the end the reason i'm ok with this is because we are still setting the vendor specific qcomm low latency flag. It's still missing the installation of the other targets in prepare-deps.

2023-04-22 14:33 UTC, ShootingKing-AM commented
Updated deps ?

2023-04-23 02:52 UTC, zarik5 approved these changes

2023-04-24 06:13 UTC, merged

2023-05-09 06:00 UTC, ShootingKing-AM commented
https://github.com/googlevr/cardboard/pull/400 Upstream updated, cardboard-sdk can now be built for x86, x86_64 (instructions are now added to https://developers.google.com/cardboard/develop/c/quickstart#enable_android_studio_x86_emulator). 

Those changes have to be made manually to sdk codebase (to enable building) which are readily available @ https://github.com/ShootingKing-AM/cardboard/tree/phonevr