Add Flatpak
alvr-org/ALVR pull request #1683
Opened 2023-06-14 18:58 UTC by CharlieQLe

This is an in-progress PR for a Flatpak build of ALVR for the Steam Flatpak. At the moment, it doesn't actually succeed because it can't find several dependencies, such as x264 and Cuda. It also targets the stable release at the moment, but that can be changed if needed.

Right now, the Flatpak pulls dependencies over the network during the build process. Ideally, the dependencies should be supplied within the manifest as to allow an offline build if needed. However, the Flatpak Cargo Generator script for generating the source manifests for all of the Cargo modules does not seem to work with Cargo modules fetched from Git repositories. If the script is updated to support this usecase, then the manifest should be updated to include the dependencies.

2023-06-14 20:59 UTC, CharlieQLe commented
I've added x264, but the linker cites a ton of undefined references and fails to compile `alvr_server`.

2023-06-14 21:30 UTC, Vixea commented on packaging/flatpak/README.md
> +git clone https://github.com/CharlieQLe/alvr-flatpak.git
Don't forget to edit this

2023-06-28 06:56 UTC, Vixea commented
this needs to be moved into xtask and I think it would be fine to just leave lto off

2023-06-28 16:09 UTC, zarik5 requested changes
Documentation regarding the build of flatpak should go in "Build from source" page in the wiki.

2023-06-28 21:43 UTC, CharlieQLe commented
> Documentation regarding the build of flatpak should go in "Build from source" page in the wiki.

I added a dedicated Flatpak wiki page. I feel that while building it could go into "Build from source", it would be better to have all the Flatpak information centralizing in one location where its shortcomings are listed, just so it isn't scattered across the wiki.

2023-06-29 11:00 UTC, Meister1593 commented on wiki/Flatpak.md
> +Various SteamVR utilities such as [WlxOverlay](https://github.com/galister/WlxOverlay) and [OpenVR-AdvancedSettings](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings) cannot run wi
Technically, i ran unpacked wlxoverlay into available dir from inside steam runtime (sh) and it ran almost flawlessly

It's not the same as installing to flatpak obviously, but as a workaround for now works

2023-07-02 05:35 UTC, Vixea commented
I'm going to merge in it's current state within the next 24 hours, though for the desktop file we couldn't you just cp the file to correct location or use install?

2023-07-02 05:39 UTC, CharlieQLe commented
> I'm going to merge in it's current state within the next 24 hours, though for the desktop file we couldn't you just cp the file to correct location or use install?

A script could be provided that copies the file and then launches the ALVR Dashboard, but it would have to run via the terminal once. The desktop file can't be copied to the host during the install as far as I know, and that just seems to be a limitation of Flatpak.

2023-07-02 05:43 UTC, Vixea commented
it seems like you can do it using build-commands aka
```
      "build-commands": [
        "install -Dm644 flatpak/io.github.TTimo.GtkRadiant.desktop /app/share/applications/io.github.TTimo.GtkRadiant.desktop",
      ],
      ```
      https://github.com/flathub/flathub/pull/3682/files
      as in example, can you not do this?

2023-07-02 20:08 UTC, CharlieQLe commented
That's not possible since `/app/share/applications` is read-only, and Flatpak creates all the symlinks to the desktop files when the application is installed, not an extension.

2023-07-03 02:04 UTC, Vixea commented
Ok then I guess it will stay as is

2023-07-03 03:57 UTC, zarik5 approved these changes

2023-07-03 03:58 UTC, merged

2023-07-03 03:59 UTC, Vixea commented
Thanks for your work, please take a break and enjoy you have done something that many alvr contributors have thought was impossible, ;D