Update Flatpak docs
alvr-org/ALVR pull request #1724
Opened 2023-07-03 16:10 UTC by CharlieQLe

Updated the build command to grant Flatpak Builder access to see the directory and updated the wiki.

2023-07-04 03:13 UTC, zarik5 requested changes

2023-07-04 03:13 UTC, zarik5 commented on wiki/Installation-guide.md
> +
Move this just below `Appimage` and above `Portable tar.gz`. I believe Flatpack is still a better choice than the tar.gz.

2023-07-10 17:39 UTC, Vixea commented
Make sure to include the fact that depending on where it is on a disk can change what command to run and show both

2023-07-10 19:05 UTC, CharlieQLe commented
> Make sure to include the fact that depending on where it is on a disk can change what command to run and show both

Should be good now. There was a typo in the original build command as well, which used `command` instead of `filesystem`.

2023-07-10 19:50 UTC, merged