Added basic toggle - cabled mode for devices
alvr-org/ALVR pull request #1877
Opened 2023-10-28 20:58 UTC by Meister1593

Appears for each device, and when toggled - automatically adds local ip, disables client discovery and switches to TCP.
When disabled, it removes local ip (though really not that necessary, still did it), enables client discovery, and leaves TCP as is (because alvr doesn't know about previous state, it's safer to just leave it as is).

Supposed to be very easy and useful toggle to not force people to go and learn where those settings are.

In addition, i made label a hyperlink so people can check out what they need to be able to use that toggle.

I think that's my first "real" pr so any comments about how to do things better (especially when writing settings).

![image](https://github.com/alvr-org/ALVR/assets/7141787/8f517c31-4890-4564-aa3d-c4290e929500)

2023-10-28 23:20 UTC, l33tlinuxh4x0r commented
I would change the wording from Cabled to "Use USB" or "Use Cable" for the toggle switch.

2023-10-28 23:36 UTC, Meister1593 commented
Also noticed this, unsure why spacing doesnt get enforced for all elements, only for last one
![image](https://github.com/alvr-org/ALVR/assets/7141787/ff2bb922-31fc-4226-9f03-9b36fe501e9e)

2023-10-28 23:42 UTC, Meister1593 commented
> I would change the wording from Cabled to "Use USB" or "Use Cable" for the toggle switch.

done, changed to `Use Cable`

2023-10-29 01:05 UTC, Meister1593 commented
I also tried going into presets area (creating single toggle for multiple paths) and doing some things with them but i got too deep with creating boolean option within it and in the end it didn't work unfortunately

2023-10-29 01:34 UTC, l33tlinuxh4x0r commented
> Also noticed this, unsure why spacing doesnt get enforced for all elements, only for last one ![image](https://user-images.githubusercontent.com/7141787/278842092-ff2bb922-31fc-4226-9f03-9b36fe501e9e.png)

I think that I found the issue... check line 118 of file /alvr/dashboard/src/dashboard/components/connections.rs
`Grid::new(2).num_columns(2).show(ui, |ui| {`
try changing it to 
`Grid::new(2).num_columns(3).show(ui, |ui| {`

just a guess as I haven't compiled it yet. I will reboot to linux and try to compile it and see.

2023-10-29 05:36 UTC, l33tlinuxh4x0r commented
Ignore last post, it breaks things. I tested and found a better fix. This should probably be implemented anyway so that you can always see everything. I set the minimum window size to the default window size so you can make the window bigger but not smaller. I changed /alvr/dashboard/src/main.rs after line 91 `initial_window_size: Some(egui::vec2(870.0, 600.0)),`
I added:
```rust
min_window_size: Some(egui::vec2(870.0, 600.0)),
```

2023-10-29 06:05 UTC, Meister1593 commented
> Ignore last post, it breaks things. I tested and found a better fix. This should probably be implemented anyway so that you can always see everything. I set the minimum window size to the default window size so you can make the window bigger but not smaller. I changed /alvr/dashboard/src/main.rs after line 91 `initial_window_size: Some(egui::vec2(870.0, 600.0)),` I added:
> 
> ```rust
> min_window_size: Some(egui::vec2(870.0, 600.0)),
> ```

it works, though not sure if hi-dpi users (steam deck users, for example) will like it

2023-10-30 00:38 UTC, l33tlinuxh4x0r commented
> > Ignore last post, it breaks things. I tested and found a better fix. This should probably be implemented anyway so that you can always see everything. I set the minimum window size to the default window size so you can make the window bigger but not smaller. I changed /alvr/dashboard/src/main.rs after line 91 `initial_window_size: Some(egui::vec2(870.0, 600.0)),` I added:
> > ```rust
> > min_window_size: Some(egui::vec2(870.0, 600.0)),
> > ```
> 
> it works, though not sure if hi-dpi users (steam deck users, for example) will like it

For what it is worth I tried making elements specific sizes too but the main window ignores this. That is the only thing that I could see that worked. Does anyone have a steam deck that can post a screenshot of how big the window looks on it?

2023-10-30 05:06 UTC, zarik5 commented
I believe we should arrange elements (labels/buttons) on two rows per client.

2023-10-30 05:08 UTC, zarik5 commented
Another option is to put the switch inside the Edit client dialog box.

2023-10-30 05:11 UTC, zarik5 requested changes

2023-10-30 05:11 UTC, zarik5 commented on alvr/packets/src/lib.rs
> +    ToggleCabled,
I believe this variant should take a bool. It's because the behavior might get confusing if there are two dashboards concurrently calling this.

2023-11-01 08:17 UTC, Meister1593 commented
![image](https://github.com/alvr-org/ALVR/assets/7141787/8142f148-919f-4e95-b14f-3c37b4bbfc70)
Finalized UI look

2023-11-01 10:04 UTC, l33tlinuxh4x0r commented
> ![image](https://user-images.githubusercontent.com/7141787/279615829-8142f148-919f-4e95-b14f-3c37b4bbfc70.png) Finalized UI look

Looks great!

2023-11-01 10:40 UTC, zarik5 commented
For symmetry i believe we should also put a frame around the new clients individually.

2023-11-01 11:24 UTC, Meister1593 commented
> For symmetry i believe we should also put a frame around the new clients individually.

You mean the ones that you need to trust first? That could be arranged, yes, i forgot about them

2023-11-01 11:45 UTC, Meister1593 commented
![image](https://github.com/alvr-org/ALVR/assets/7141787/2d3629e7-c10b-4726-9708-60b13ec8525e)

2023-11-02 03:05 UTC, zarik5 commented
Looking awesome! 😄

2023-11-02 03:06 UTC, zarik5 approved these changes

2023-11-02 03:07 UTC, merged

2023-11-02 03:07 UTC, l33tlinuxh4x0r commented
Agreed.

> Looking awesome! 😄