Support AV1 encoding using AMF on Windows
alvr-org/ALVR pull request #1967
Opened 2024-01-26 22:59 UTC by barnabwhy

It seems to be working nicely from my testing with a Quest 3 and RX 7700XT.

There's a couple of changes to settings, namely:
- Removed "(VAAPI only)" from AV1 codec name.
- Renamed "Enable VBAQ" to "Enable VBAQ/AQ" and added help text explaining that it's AQ on AV1 and VBAQ on the other two.

With this I also updated AMF to v1.4.33, which may bring some improvements elsewhere. (It may be worth looking into the "New AVC / HEVC encoder rate control methods" added in v1.4.28)

2024-01-26 23:03 UTC, Vixea requested changes

2024-01-26 23:03 UTC, Vixea commented on alvr/session/src/settings.rs
> +    #[schema(strings(display_name = "AV1"))]
Please add AMD only

2024-01-30 03:26 UTC, zarik5 commented
I think this PR should be split between AMF headers upgrade and the rest, because the changes are hard to navigate.

2024-01-30 13:19 UTC, phobos2077 commented
> I think this PR should be split between AMF headers upgrade and the rest, because the changes are hard to navigate.

IMO it's not hard to navigate. Why would you split PR if it all related? Unless the headers upgrade is not required for the rest.

2024-01-30 14:37 UTC, zarik5 commented
If anything else, i'd like to split the PR because of the "single concern" principle.

2024-02-02 22:51 UTC, Vixea commented
^ it would be much easier to figure out what the issue is if an upgrade of the headers happens to cause issues however unlikely

2024-02-04 11:18 UTC, Vixea reviewed
I changed my mind though I would like a warning when a user enables pre-analysis because it incurs a latency penalty... something you generally don't want in a realtime vr driver.

2024-02-10 11:34 UTC, zarik5 commented
I think the PR can be rebased @barnabwhy

2024-02-11 04:50 UTC, zarik5 approved these changes
LGTM

2024-02-12 02:17 UTC, merged

2024-04-19 09:31 UTC, MommasLittleHelper commented
Does AV1 also work on Windows with Nvidia cards? 🤔

2024-04-19 10:12 UTC, zarik5 commented
@MommasLittleHelper Noone contributed that yet