fix(client): reconnect default audio device on disconnect
alvr-org/ALVR pull request #2025
Opened 2024-03-10 13:31 UTC by Okabintaro

This makes it possible to plug in your headphones without restarting the client(Fixes #1092).

I am still new to rust and not sure if this is best way to solve this but it works for me and it annoyed me a bunch. Open for suggestions!

2024-03-11 08:46 UTC, galister requested changes
I would avoid adding an additional Mutex here. Instead, maybe put the `sample_buffer` and `state` together in a new struct, and make them share the existing `Arc<Mutex>`.

For example:

```rust
pub struct AudioLoopData<D> {
    sample_buffer: VecDeque<f32>,
    data: D
}
```

```rust
pub fn receive_samples_loop<D>(
    [...]
    data: Arc<Mutex<AudioLoopData<D>>>
```

2024-03-11 10:40 UTC, Okabintaro commented
There are some reasons why I did it that way but I think it could be possible:

1. The callback that sets the state can potentially be called from yet another thread, which could result in a deadlock between the [on_audio_ready](https://docs.rs/oboe/latest/oboe/trait.AudioOutputCallback.html#tymethod.on_audio_ready) and the [on_error_before_close](https://docs.rs/oboe/latest/oboe/trait.AudioOutputCallback.html#method.on_error_before_close) if they would share a single mutex.

2. I was following the example of the `AudioPlayBackData` from above which also introduced a mutex for that state. So you could argue this is consistent: https://github.com/alvr-org/ALVR/blob/455d9d535f7565744cea3349077987c5670dbcc2/alvr/client_core/src/audio.rs#L16-L20

3. I also think having them separate is good because the state one will be locked quite often by the loop that puts in the data for the other callback to read: https://github.com/alvr-org/ALVR/blob/455d9d535f7565744cea3349077987c5670dbcc2/alvr/client_core/src/audio.rs#L191

Maybe one could use an atomic to make things more performant but it's working fine as it is at the moment.

You could workaround 1 probably, by using [on_error_after_close](https://docs.rs/oboe/latest/oboe/trait.AudioOutputCallback.html#method.on_error_after_close) which should get called in the same thread than the [on_audio_ready](https://docs.rs/oboe/latest/oboe/trait.AudioOutputCallback.html#tymethod.on_audio_ready).

2024-03-13 06:38 UTC, zarik5 requested changes
Overall LGTM!

2024-03-13 06:38 UTC, zarik5 commented on alvr/client_core/src/audio.rs
> +        _error: oboe::Error,
Remove leading underscore in `_error`

2024-03-13 06:38 UTC, zarik5 commented on alvr/client_core/src/audio.rs
> +    };
Since you are matching all variants of the enum, don't use wildcard `_`

2024-03-13 17:47 UTC, Okabintaro commented
Thanks for the review!

I've been using this for quite some time on my Quest 2 but would maybe like someone else to test it too.
For some reason recently the quest microphone input just stops working and I can't even bring up the quest dashboard app to restart ALVR. I am not sure if this is just the Quest being buggy or these changes. After rebooting things work fine again.

2024-03-14 07:53 UTC, galister approved these changes

2024-03-14 08:01 UTC, zarik5 approved these changes

2024-03-14 08:02 UTC, merged