chore: add c++ autoformatter
alvr-org/ALVR pull request #2182
Opened 2024-06-08 00:45 UTC by The-personified-devil

2024-06-08 10:10 UTC, zarik5 commented
You should either make a new CI workflow or rename "Rustfmt" to just "Check formatting"

2024-06-26 11:30 UTC, zarik5 requested changes
Remove symbols paths when possible. I use a rule, where object are added directly to `use`, and for functions you add the parent module, so the usage would be `parent::func()`. It's a bit arbitrary and comments on this are welcome.

2024-06-26 11:30 UTC, zarik5 commented on alvr/xtask/src/format.rs
> +    }
Since the expression is a bit complex, split into two booleans and then combine with &&

2024-06-26 11:30 UTC, zarik5 commented on alvr/xtask/src/format.rs
> +            })
I think you could use `matches!()` instead, or `["your", "matches"].contains(name)`. same for the expression below

2024-06-26 11:30 UTC, zarik5 commented on alvr/xtask/src/format.rs
> +    let cpp_dir = afs::workspace_dir().join("alvr/server/cpp/");
You can use `afs::crate_dir()`

2024-06-26 11:30 UTC, zarik5 commented on alvr/xtask/src/format.rs
> +            panic!("file {} missing final newline", path.display());
You can use string interpolation: `{path}`. same below

2024-06-26 17:13 UTC, zarik5 approved these changes
I would point out a few more coding style nits but i'd say we can merge now.

2024-06-27 03:02 UTC, The-personified-devil commented
Yet again rebase merge, cuz it makes more sense as both commits stand on their own

2024-06-27 03:14 UTC, Vixea approved these changes

2024-06-27 03:30 UTC, merged