fix: :bug: Fix and rework logging
alvr-org/ALVR pull request #2351
Opened 2024-08-22 15:46 UTC by zarik5

2024-08-22 19:19 UTC, The-personified-devil commented
I mean I didn't catch it in code review either, but how do you keep managing to not test stuff

2024-08-26 22:03 UTC, The-personified-devil requested changes

2024-08-26 22:26 UTC, zarik5 commented on alvr/server_openvr/cpp/alvr_server/Controller.cpp
> +    Debug("Controller::constructor");
Fair

2024-08-26 22:29 UTC, zarik5 commented on alvr/server_openvr/cpp/alvr_server/Controller.cpp
> +    Debug("Controller::RegisterButton id=%llu", id);
whops

2024-08-26 22:30 UTC, zarik5 commented on alvr/server_core/src/connection.rs
> +    debug!(target: "server_core", "Connection established with {client_hostname}");
uhm, that was me testing the intended syntax that is then abstracted away with the macros I defined in alvr_common. I forgot to reconvert this to our custom macros

2024-08-26 22:43 UTC, zarik5 commented on alvr/dashboard/src/dashboard/components/logs.rs
> +        let color = if let EventType::Log(entry) = &event.event_type {
Should I split it as `color` and `should_print` variables?

2024-08-26 22:47 UTC, The-personified-devil commented on alvr/dashboard/src/dashboard/components/logs.rs
> +        let color = if let EventType::Log(entry) = &event.event_type {
leave it, it's now an easter egg

2024-08-27 18:23 UTC, The-personified-devil approved these changes

2024-08-27 18:24 UTC, merged