Support Meta Quest 3 native resolution
alvr-org/ALVR pull request #2425
Opened 2024-09-25 21:33 UTC by nowak-pl

Meta Quest 3 has LCD panels with per eye resolution of 2064 x 2208. Setting this resolution is currently impossible as it gets rounded down to 2048 x 2208. This pull request relaxes resolution alignment from 32 to 16 pixels.

2024-09-25 22:01 UTC, zarik5 commented
The Nvidia encoder does not support resolutions that are not a multiple of 32, with the exception of a few standard resolutions like HD, FHD, QHD etc. if we request a resolution which is not a multiple of 32 the image will be stretched to fill the next up multiple of 32, which will result in a blurry image.

2024-09-25 22:08 UTC, nowak-pl commented
We are talking about per-eye resolution, encoding is done on width * 2 so it is divisible by 32. Maybe align to 16 only for width with height kept at 32. With the changes and nvidia gpu 2064 x 2208 works for me nicely.

2024-09-25 22:30 UTC, zarik5 commented
True, for width we can align to 16 per eye. I personally don't believe this has any practical benefit, as I believe that "native screen resolution" as magical numbers don't make sense. The reason is the image is distorted because of lens correction, which even causes inconsistent pixel densities across the eye view, and only a portion of the screen is often used to render the frame.

2024-09-25 22:35 UTC, zarik5 requested changes

2024-09-25 22:35 UTC, zarik5 commented on alvr/server_core/src/connection.rs
> +        UVec2::new(align16(res.x), align16(res.y))
Please revert vertical alignment

2024-09-26 00:50 UTC, zarik5 approved these changes

2024-09-26 01:21 UTC, The-personified-devil commented
> The Nvidia encoder does not support resolutions that are not a multiple of 32

huh, h264 macroblocks are 16x16

2024-09-26 17:24 UTC, Vixea commented
CI failure is unrelated I'm guessing a cargo apk update or something, is now enforcing a specific platform version 32

2024-09-26 18:59 UTC, zarik5 commented
> huh, h264 macroblocks are 16x16

@The-personified-devil HEVC macroblock size is 64x64. I think the macroblock side doesn't matter, it's a limitation of the API itself

2024-09-26 19:03 UTC, The-personified-devil commented
>   @The-personified-devil HEVC macroblock size is 64x64. I think the macroblock side doesn't matter, it's a limitation of the API itself

Yes it does, 1080p and co are only supported because the encoder just adds a black bar that it then cuts out during decoding again. So if the encoder wants stuff to be aligned by macroblocks (which it should, dunno why it wouldn't, except for special resolutions) and we would have to conform to that for all codecs that we have. So with the 64 for hevc we couldn't lower the per eye to below 32.

2024-09-26 19:05 UTC, zarik5 commented
Hm. Welp, so should we increase the alignment to 64?

2024-09-26 19:07 UTC, The-personified-devil commented
> Hm. Welp, so should we increase the alignment to 64

No because as we noticed per eye gets multiplied to 2, so 32 alignment per eye would be enough, and that's what it already is. Only thing I'm not sure about is how foveated encoding handles all of that/how the encoders have been dealing with it or are we actually aligning that properly?

2024-09-26 21:42 UTC, zarik5 commented
> No because as we noticed per eye gets multiplied to 2, so 32 alignment per eye would be enough, and that's what it already is.

Nope, vertical resolution is still wrong.

> Only thing I'm not sure about is how foveated encoding handles all of that/how the encoders have been dealing with it or are we actually aligning that properly?

We assign a new resolution that is a multiple of 32 horizontally and vertically.

2024-09-27 13:10 UTC, zarik5 requested changes

2024-09-27 13:10 UTC, zarik5 commented on alvr/server_core/src/connection.rs
> +        UVec2::new(align16(res.x), align32(res.y))
Make horizontal alignment by 32 and vertical alignment by 64.

2024-10-05 14:40 UTC, zarik5 commented
@nowak-pl ping?

2024-10-23 19:41 UTC, closed without merging

2026-01-31 01:57 UTC, epicawesomesauce commented
any reason for this not happening in the end?